function ex_KeyPressFcn
% Creates figure with text fields to display keypress event data.
% Use check box to control writing events to base workspace.

% Copyright 2010 The MathWorks, Inc.

figure('NumberTitle','off',...
       'Name','Key Press Event Data Viewer',...
       'Menubar','none',...
       'Position',[560 728 560 200],...
       'KeyPressFcn',@dispkeyevent);
uicontrol('Style','text',...
          'String','Type a character to see its keyboard data.',...
          'FontSize',10,...
          'FontWeight','bold',...
          'Units','normalized','Position',[.25 .8 .5 .1]);
uicontrol('Style','text',...
          'String','Character',...
          'FontWeight','bold',...
          'Units','normalized','Position',[.1 .6 .24 .1]);
uicontrol('Style','text',...
          'String','Char Code',...
          'FontWeight','bold',...
          'Units','normalized','Position',[.3 .6 .24 .1]);
uicontrol('Style','text',...
          'String','Key',...
          'FontWeight','bold',...
          'Units','normalized','Position',[.5 .6 .24 .1]);
uicontrol('Style','text',...
          'String','Modifier',...
          'FontWeight','bold',...
          'Units','normalized','Position',[.7 .6 .24 .1]);

htxt6 = uicontrol('Style','text',...
                 'String','',...
                 'FontWeight','normal',...
                 'Units','normalized','Position',[.1 .375 .24 .1]);
htxt7 = uicontrol('Style','text',...
                 'String','',...
                 'FontWeight','normal',...
                 'Units','normalized','Position',[.3 .375 .24 .1]);
htxt8 = uicontrol('Style','text',...
                 'String','',...
                 'FontWeight','normal',...
                 'Units','normalized','Position',[.5 .375 .24 .1]);
htxt9 = uicontrol('Style','text',...
                 'String','',...
                 'FontWeight','normal',...
                 'Units','normalized','Position',[.7 .375 .24 .1]);
hchk1 = uicontrol('Style','checkbox',...
                 'String','Write key data to workspace',...
                 'Units','normalized','Position',[.65 .05 .3 .1],...
                 'Value',0);

    function dispkeyevent(~, event)
    % Display keypress info in GUI and return event struct if requested
    % event - Structure containing keypress identifiers

    c = event.Character;
    if c == '.'
        set(htxt6,'String','Bingo')
    else
        set(htxt6,'String',c)
    end
    set(htxt7,'String',num2str(double(c)))
    if strcmp(event.Key,'pageup')
        set(htxt8,'String','move down');
    else if strcmp(event.Key,'pagedown')
            set(htxt8,'String','move up');
        else
            set(htxt8,'String',event.Key)
        end
    end
    set(htxt9,'String',event.Modifier)
    if get(hchk1,'Value')
        assignin('base','keystruct',event)
    end
    end
end
             